import 'package:expense_tracking_prd/models/client_model.dart';
import 'package:expense_tracking_prd/models/expense_model.dart';
import 'package:expense_tracking_prd/models/project_model.dart';
import 'package:expense_tracking_prd/models/user_model.dart';
import 'package:expense_tracking_prd/models/user_role.dart';

class TestFixtures {
  static const List<UserModel> testUsers = [
    UserModel(
      id: 'usr_adm_01',
      name: 'Eleanor Vance',
      email: 'admin@pfis.com',
      role: UserRole.mainAdmin,
      department: 'Corporate Governance',
      designation: 'Managing Director / Super Admin',
      isActive: true,
      isApproved: true,
      assignedProjectIds: ['proj_01', 'proj_02', 'proj_03', 'proj_04', 'proj_05'],
    ),
    UserModel(
      id: 'usr_mgr_01',
      name: 'Sarah Jenkins',
      email: 'manager@pfis.com',
      role: UserRole.projectManager,
      department: 'Project Management & Field Ops',
      designation: 'Senior Project Manager',
      isActive: true,
      isApproved: true,
      assignedProjectIds: ['proj_01', 'proj_02'],
    ),
    UserModel(
      id: 'usr_emp_01',
      name: 'Fahim Ahmed',
      email: 'fahim@pfis.com',
      role: UserRole.projectMember,
      department: 'Field Survey & Operations',
      designation: 'Field Team Lead',
      isActive: true,
      isApproved: true,
      assignedProjectIds: ['proj_01'],
    ),
    UserModel(
      id: 'usr_emp_03',
      name: 'Karim Ullah',
      email: 'karim@pfis.com',
      role: UserRole.projectMember,
      department: 'Water & Sanitation Team',
      designation: 'Field Enumeration Specialist',
      isActive: true,
      isApproved: true,
      assignedProjectIds: ['proj_03'],
    ),
  ];

  static final List<ProjectModel> testProjects = [
    ProjectModel(
      id: 'proj_01',
      projectId: 'PRJ-2026-001',
      name: 'Enterprise Cloud ERP Platform',
      description: 'Modern microservices-based ERP migration with multi-tenant billing, inventory, and HR automation.',
      client: 'Apex Technologies Inc.',
      clientType: ClientType.private,
      assignmentType: AssignmentType.directConsultancy,
      grossProjectValue: 2500000.0,
      taxStatus: TaxStatus.included,
      taxRate: 0.10,
      expectedNetRevenue: 2250000.0,
      advanceReceived: 500000.0,
      amountReceived: 1500000.0,
      amountReceivable: 1000000.0,
      budget: 2080000.0,
      categoryBudgets: {
        'equipment': 300000.0,
        'transportation': 450000.0,
        'food': 250000.0,
        'accommodation': 400000.0,
        'officecost': 200000.0,
        'officebenefit': 480000.0,
      },
      estimatedRemainingCost: 580000.0,
      officeBenefitRate: 0.30,
      startDate: DateTime(2026, 1, 15),
      endDate: DateTime(2026, 11, 30),
      teamMemberIds: ['usr_emp_01', 'usr_mgr_01', 'usr_fin_01', 'usr_adm_01'],
      status: ProjectStatus.ongoing,
      progressPercentage: 65.0,
      progressUpdatedAt: DateTime(2026, 9, 20, 14, 30),
      progressUpdatedByName: 'Sarah Jenkins',
      progressUpdatedById: 'usr_mgr_01',
      revenueEntries: [
        RevenueEntry(
          id: 'rev_01',
          projectId: 'proj_01',
          amount: 500000.0,
          date: DateTime(2026, 2, 1),
          note: 'Advance Mobilization Payment',
          createdBy: 'David Chen',
        ),
      ],
    ),
  ];

  static final List<ExpenseModel> testExpenses = [
    ExpenseModel(
      id: 'exp_fahim_01',
      employeeId: 'usr_emp_01',
      employeeName: 'Fahim Ahmed',
      projectId: 'proj_01',
      projectName: 'Enterprise Cloud ERP Platform',
      amount: 40000.0,
      baseCost: 36000.0,
      taxRate: 10.0,
      taxAmount: 4000.0,
      officeBenefitAmount: 12000.0,
      currency: 'BDT',
      categoryId: 'cat_equip',
      categoryName: 'Equipment',
      categoryIcon: 'hardware',
      note: 'AWS GPU cluster and dedicated staging server infrastructure.',
      date: DateTime(2026, 9, 5),
      hasReceipt: true,
      status: ExpenseStatus.approved,
      createdAt: DateTime(2026, 9, 5, 11, 30),
      equipmentDetails: const EquipmentDetails(
        equipmentType: 'AWS Cloud Compute & GPU Cluster',
        isRental: true,
        quantity: 4,
        rentalAmount: 40000.0,
        rentalPeriod: '1 Month',
      ),
    ),
    ExpenseModel(
      id: 'exp_fahim_02',
      employeeId: 'usr_emp_01',
      employeeName: 'Fahim Ahmed',
      projectId: 'proj_01',
      projectName: 'Enterprise Cloud ERP Platform',
      amount: 35000.0,
      officeBenefitAmount: 10500.0,
      currency: 'BDT',
      categoryId: 'cat_trans',
      categoryName: 'Transportation',
      categoryIcon: 'transport',
      note: 'Client onsite technical sprint planning & team commute.',
      date: DateTime(2026, 9, 12),
      hasReceipt: false,
      status: ExpenseStatus.pending,
      justificationStatus: JustificationStatus.required,
      createdAt: DateTime(2026, 9, 12, 18, 45),
      transportationDetails: const TransportationDetails(
        transportationType: TransportationType.cng,
        fromLocation: 'Tech HQ',
        toLocation: 'Client Corporate Tower',
        distanceKm: 45.0,
        fuelCost: 20000.0,
        otherTransportCost: 15000.0,
      ),
    ),
    ExpenseModel(
      id: 'exp_fahim_03',
      employeeId: 'usr_emp_01',
      employeeName: 'Fahim Ahmed',
      projectId: 'proj_01',
      projectName: 'Enterprise Cloud ERP Platform',
      amount: 25000.0,
      officeBenefitAmount: 7500.0,
      currency: 'BDT',
      categoryId: 'cat_food',
      categoryName: 'Food',
      categoryIcon: 'meal',
      note: 'Dev team sprint release milestone dinner & refreshments.',
      date: DateTime(2026, 9, 14),
      hasReceipt: false,
      status: ExpenseStatus.pending,
      justificationStatus: JustificationStatus.required,
      createdAt: DateTime(2026, 9, 14, 21, 15),
      foodDetails: const FoodDetails(
        location: 'Tech Hub Cafeteria',
        attendees: 'Fahim, 7 Fullstack Engineers',
        numberOfPeople: 8,
        mealType: 'Sprint Dinner',
        exceedsFoodAllowance: false,
      ),
    ),
    ExpenseModel(
      id: 'exp_karim_01',
      employeeId: 'usr_emp_03',
      employeeName: 'Karim Ullah',
      projectId: 'proj_01',
      projectName: 'Enterprise Cloud ERP Platform',
      amount: 50000.0,
      officeBenefitAmount: 15000.0,
      currency: 'BDT',
      categoryId: 'cat_trans',
      categoryName: 'Transportation',
      categoryIcon: 'transport',
      note: 'Partner hospital pilot travel.',
      date: DateTime(2026, 9, 8),
      hasReceipt: false,
      status: ExpenseStatus.approved,
      createdAt: DateTime(2026, 9, 8, 19, 00),
      transportationDetails: const TransportationDetails(
        transportationType: TransportationType.local,
        fromLocation: 'BioHealth Lab',
        toLocation: 'Partner Hospitals',
        distanceKm: 140.0,
      ),
    ),
    ExpenseModel(
      id: 'exp_sarah_01',
      employeeId: 'usr_mgr_01',
      employeeName: 'Sarah Jenkins',
      projectId: 'proj_01',
      projectName: 'Enterprise Cloud ERP Platform',
      amount: 15000.0,
      officeBenefitAmount: 4500.0,
      currency: 'BDT',
      categoryId: 'cat_trans',
      categoryName: 'Transportation',
      categoryIcon: 'transport',
      note: 'Executive client review commute and operational coordination.',
      date: DateTime(2026, 9, 15),
      hasReceipt: true,
      status: ExpenseStatus.approved,
      createdAt: DateTime(2026, 9, 15, 16, 30),
      transportationDetails: const TransportationDetails(
        transportationType: TransportationType.cng,
        fromLocation: 'Corporate HQ',
        toLocation: 'Client HQ',
        distanceKm: 25.0,
      ),
    ),
  ];
}
